#!/usr/bin/env python3
"""Generate the terminal character-width table shared by MonkeyMux and the client.

The MonkeyMux screen model (Go) and the xterm fork (Dart) must agree on how many
columns every code point takes, or wrapping and cursor positions diverge between
the retained model and the live client. Both tables are generated here from one
source, the Unicode Character Database bundled with Python's unicodedata module:

  remote/monkeymux/runewidth_table.go
  third_party/xterm/lib/src/utils/unicode_v11.dart
  scripts/unicode_width_table.crc32   (checked by the Go and Dart parity tests)

Run it with a Python whose unicodedata.unidata_version is UNICODE_VERSION, or
change UNICODE_VERSION to move both sides to another Unicode release. --check
reports stale outputs without writing them.
"""

import argparse
from pathlib import Path
import re
import sys
import unicodedata
import zlib

UNICODE_VERSION = '16.0.0'
ROOT = Path(__file__).resolve().parents[1]
GO_PATH = ROOT / 'remote/monkeymux/runewidth_table.go'
DART_PATH = ROOT / 'third_party/xterm/lib/src/utils/unicode_v11.dart'
DIGEST_PATH = ROOT / 'scripts/unicode_width_table.crc32'
KITTY_SOURCE = ROOT / 'remote/monkeymux/vtscreen_render.go'
MAX_CODE_POINT = 0x10FFFF

# Emoji modifiers only follow an emoji base. Host width libraries count the
# modified pair as the base's two columns, so a modifier adds none.
EMOJI_MODIFIERS = range(0x1F3FB, 0x1F3FF + 1)
# Hangul medial vowels and final consonants join the preceding leading consonant.
HANGUL_JAMO_MEDIAL_FINAL = range(0x1160, 0x11FF + 1)
SOFT_HYPHEN = 0x00AD


def kitty_placeholder_diacritics(source=KITTY_SOURCE):
    """The Kitty unicode-placeholder row/column marks, which are zero width."""
    text = source.read_text()
    match = re.search(r'var kittyPlaceholderDiacritics = \[\]rune\{(.*?)\n\}', text, re.S)
    if not match:
        raise SystemExit(f'kittyPlaceholderDiacritics not found in {source}')
    return frozenset(int(value, 16) for value in re.findall(r'0x([0-9A-Fa-f]+)', match.group(1)))


def code_point_width(code_point, kitty_diacritics):
    """Columns a code point occupies, by wcwidth's rules plus the exceptions above."""
    if code_point < 0x20 or 0x7F <= code_point < 0xA0:
        return 0
    if code_point in kitty_diacritics or code_point in EMOJI_MODIFIERS:
        return 0
    char = chr(code_point)
    if unicodedata.category(char) in ('Mn', 'Me', 'Cf') and code_point != SOFT_HYPHEN:
        return 0
    if code_point in HANGUL_JAMO_MEDIAL_FINAL:
        return 0
    if unicodedata.east_asian_width(char) in ('W', 'F'):
        return 2
    return 1


def width_table(kitty_diacritics):
    return bytes(code_point_width(cp, kitty_diacritics) for cp in range(MAX_CODE_POINT + 1))


def width_ranges(table):
    """(first, last, width) for every run of code points whose width is not 1."""
    ranges = []
    start = None
    for cp, width in enumerate(table):
        if start is not None and width != table[start]:
            ranges.append((start, cp - 1, table[start]))
            start = None
        if start is None and width != 1:
            start = cp
    if start is not None:
        ranges.append((start, len(table) - 1, table[start]))
    return ranges


def hex_code_point(cp):
    return f'0x{cp:04X}'


def render_go(ranges):
    rows = []
    for i in range(0, len(ranges), 4):
        cells = ', '.join(f'{{{hex_code_point(lo)}, {hex_code_point(hi)}, {w}}}' for lo, hi, w in ranges[i:i + 4])
        rows.append(f'\t{cells},')
    body = '\n'.join(rows)
    return f'''// Code generated by scripts/generate_unicode_width_tables.py; DO NOT EDIT.

package main

// runeWidthUnicodeVersion is the Unicode release runeWidthRanges was built
// from. The client's third_party/xterm/lib/src/utils/unicode_v11.dart is
// generated from the same table, and both sides check it against
// scripts/unicode_width_table.crc32 so the screen model and the client wrap
// and advance the cursor identically.
const runeWidthUnicodeVersion = "{UNICODE_VERSION}"

type runeWidthRange struct {{
	lo, hi rune
	width  uint8
}}

// runeWidthRanges lists, in order, every code point range whose width is not 1.
var runeWidthRanges = []runeWidthRange{{
{body}
}}

// runeWidth returns the number of cells a rune occupies: 0 for controls,
// combining marks, format characters and Kitty placeholder diacritics, 2 for
// East Asian wide and fullwidth characters (including emoji presentation),
// 1 otherwise.
func runeWidth(r rune) int {{
	if r >= 0x20 && r < 0x7F {{
		return 1
	}}
	lo, hi := 0, len(runeWidthRanges)-1
	for lo <= hi {{
		mid := int(uint(lo+hi) >> 1)
		switch entry := runeWidthRanges[mid]; {{
		case r < entry.lo:
			hi = mid - 1
		case r > entry.hi:
			lo = mid + 1
		default:
			return int(entry.width)
		}}
	}}
	return 1
}}
'''


def render_dart(ranges):
    # The trailing comments keep dart format from putting each value on a line.
    rows = '\n'.join(
        '  ' + ' '.join(f'{hex_code_point(lo)}, {hex_code_point(hi)}, {w},' for lo, hi, w in ranges[i:i + 3]) + ' //'
        for i in range(0, len(ranges), 3))
    return f'''// GENERATED CODE - DO NOT MODIFY BY HAND.
// Generated by scripts/generate_unicode_width_tables.py from Unicode
// {UNICODE_VERSION}. The MonkeyMux screen model's runeWidth
// (remote/monkeymux/runewidth_table.go) is generated from the same table, and
// both sides check it against scripts/unicode_width_table.crc32 so the client
// and the model wrap and advance the cursor identically. The file and class
// keep the name of the Unicode 11 table they replaced.

import 'dart:typed_data';

/// Unicode release the width table was built from.
const unicodeWidthVersion = '{UNICODE_VERSION}';

/// Every code point range whose width is not 1, in order, as
/// (first, last, width) triples.
const _widthRanges = <int>[
{rows}
];

/// Widths of the Basic Multilingual Plane, indexed by code point.
final Uint8List _bmpWidths = _buildBmpWidths();

Uint8List _buildBmpWidths() {{
  final table = Uint8List(0x10000)..fillRange(0, 0x10000, 1);
  for (var i = 0; i < _widthRanges.length; i += 3) {{
    final first = _widthRanges[i];
    if (first >= 0x10000) break;
    final last = _widthRanges[i + 1] < 0x10000 ? _widthRanges[i + 1] : 0xFFFF;
    table.fillRange(first, last + 1, _widthRanges[i + 2]);
  }}
  return table;
}}

int _rangeWidth(int codePoint) {{
  var low = 0;
  var high = _widthRanges.length ~/ 3 - 1;
  while (low <= high) {{
    final mid = (low + high) >> 1;
    if (codePoint < _widthRanges[mid * 3]) {{
      high = mid - 1;
    }} else if (codePoint > _widthRanges[mid * 3 + 1]) {{
      low = mid + 1;
    }} else {{
      return _widthRanges[mid * 3 + 2];
    }}
  }}
  return 1;
}}

class UnicodeV11 {{
  final version = unicodeWidthVersion;

  /// Number of terminal columns [codePoint] occupies: 0, 1 or 2.
  int wcwidth(int codePoint) {{
    if (codePoint < 0x20) return 0;
    if (codePoint < 0x10000) return _bmpWidths[codePoint];
    return _rangeWidth(codePoint);
  }}
}}

final unicodeV11 = UnicodeV11();
'''


def render_digest(table):
    return f'''# Generated by scripts/generate_unicode_width_tables.py. Do not edit.
# CRC-32 (IEEE) of one width byte per code point, U+0000 through U+10FFFF.
unicode {UNICODE_VERSION}
crc32 {zlib.crc32(table):08x}
'''


def outputs():
    if unicodedata.unidata_version != UNICODE_VERSION:
        raise SystemExit(
            f'unicodedata is Unicode {unicodedata.unidata_version}, expected {UNICODE_VERSION}: '
            'run with a matching Python or update UNICODE_VERSION')
    table = width_table(kitty_placeholder_diacritics())
    ranges = width_ranges(table)
    return {GO_PATH: render_go(ranges), DART_PATH: render_dart(ranges), DIGEST_PATH: render_digest(table)}


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument('--check', action='store_true', help='fail if a generated file is stale')
    args = parser.parse_args(argv)
    stale = []
    for path, text in outputs().items():
        current = path.read_text() if path.exists() else None
        if current == text:
            continue
        stale.append(path.relative_to(ROOT))
        if not args.check:
            path.write_text(text)
    if args.check and stale:
        print('stale: ' + ', '.join(map(str, stale)), file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
